# Generated by Django 3.0.6 on 2020-07-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='report_file',
            field=models.FileField(blank=True, upload_to='report/%Y/%m/%d/'),
        ),
    ]
