# Generated by Django 3.0.6 on 2020-06-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200625_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('price',), 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
    ]
