# Generated by Django 3.0.6 on 2020-07-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_report_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='report/%Y/%m/%d/'),
        ),
    ]
