# Generated by Django 3.0.6 on 2020-06-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200626_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['price'], 'verbose_name': 'Price', 'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterField(
            model_name='project',
            name='project_url',
            field=models.URLField(blank=True, null=True, verbose_name='Project URL'),
        ),
    ]
