# Generated by Django 3.0.6 on 2020-07-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='ProjectCategory',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
