# Generated by Django 3.0.6 on 2020-07-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200707_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('Ph.D.', 'Doctor of Philosophy'), ('M.Sc.', 'Masters'), ('B.Sc.', 'Bachelor'), ('12th', 'High School')], max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='qualification',
            field=models.CharField(help_text='e.g., Economist', max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='school_name',
            field=models.CharField(help_text='e.g., Tbilisi State University', max_length=250),
        ),
        migrations.AlterField(
            model_name='education',
            name='summary',
            field=models.TextField(blank=True, help_text='e.g., Diploma with honors'),
        ),
        migrations.AlterField(
            model_name='job',
            name='company',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='langskill',
            name='name',
            field=models.CharField(help_text='Ukrainian, English', max_length=250),
        ),
        migrations.AlterField(
            model_name='langskill',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='first_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='personalinfo',
            name='last_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='price',
            name='instrument',
            field=models.CharField(default='Django', max_length=250),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(help_text='Project name', max_length=250),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='price',
            name='support',
            field=models.CharField(blank=True, choices=[('Mail Support', 'Mail Support'), ('Endless Support', 'Endless Support')], default='Mail Support', max_length=250),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Content for description meta tag', max_length=250),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for keywords meta tag', max_length=250),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(help_text='Unique value for product page URL, created automatically from name.', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='e.g., C++, Python', max_length=250),
        ),
        migrations.AlterField(
            model_name='skill',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
        migrations.AlterField(
            model_name='skillset',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
