# Generated by Django 3.0.6 on 2020-07-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_comment_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Content for description meta tag', max_length=250),
        ),
        migrations.AddField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for keywords meta tag', max_length=250),
        ),
        migrations.AddField(
            model_name='price',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Content for description meta tag', max_length=250),
        ),
        migrations.AddField(
            model_name='price',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for keywords meta tag', max_length=250),
        ),
        migrations.AddField(
            model_name='skill',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Content for description meta tag', max_length=250),
        ),
        migrations.AddField(
            model_name='skill',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for keywords meta tag', max_length=250),
        ),
        migrations.AddField(
            model_name='skillset',
            name='meta_description',
            field=models.CharField(blank=True, help_text='Content for description meta tag', max_length=250),
        ),
        migrations.AddField(
            model_name='skillset',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for keywords meta tag', max_length=250),
        ),
    ]
