# Generated by Django 3.0.6 on 2020-07-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
